name = "PatentModel"
uuid = "0d45b89c-4211-41e2-a538-c101ef016184"
authors = ["SanteriVtj <santeri.vaataja@gmail.com>"]
version = "0.1.0"

[deps]
HaltonSequences = "13907d55-377f-55d6-a9d6-25ac19e11b95"
